project:
  type: book
  execute-dir: project
  output-dir: docs
  
execute: 
  freeze: auto

format:
  html:
    theme:
      - lumen
    grid: 
      sidebar-width: 350px
    fontsize: "100%"
    template-partials:
      - toc.html
    toc-title: "On this page"
  # pdf:
  #   documentclass: scrreprt
  #   mainfont: "Open Sans"
  #   fig-pos: "H"
  #   include-in-header:
  #     text: |
  #       \usepackage{float}
  #       \raggedbottom

book:
  title: "Virginia Zoning Atlas"
  repo-url: https://github.com/housingforwardva/cvpdc
  author: 
    name: "HousingForward Virginia"
    url: https://www.housingforwardva.org
  # downloads: pdf 
  date: today
  chapters:
    - index.qmd 
    - part: "Introduction"
      chapters:
        - part-1-1.qmd # Introduction
        - part-1-2.qmd # Methodology
        - part-1-3.qmd # Things to keep in mind
    - part: "Hampton Roads"
      chapters:
        - part-2-1.qmd # Summary
        - part-2-2.qmd # Findings
  # - part: "Appendix"

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false
    
# comments: 
#   hypothesis: true