# About {.unnumbered}

The Virginia Zoning Atlas is a research project of HousingForward Virginia with support from the Mercatus Center at George Mason University. The Atlas is an ongoing collaborative effort to map and standardize zoning across the Commonwealth. The Atlas helps visualize the impact of zoning on housing development and allows for cross-jurisdictional comparisons for deeper zoning analysis.

The Virginia Zoning Atlas is part of the larger National Zoning Atlas, which "aims to depict key aspects of zoning codes in an online, user-friendly map.  It will enable comparisons across jurisdictions, illuminate regional and statewide trends, and strengthen national planning for housing production, transportation infrastructure, and climate response." 


# HousingForward Virginia
[HousingForward Virginia](https://www.housingforwardva.org) is the Commonwealth’s trusted resource for affordable housing data and actionable insights. Advocates, planners, developers, and mission-aligned organizations rely on us to help them build connections and advance their work. With our tools, they’re able to better identify needs, influence decision makers, and ultimately increase access to affordable housing for all.

# The Mercatus Center at George Mason University
[The Mercatus Center](https://www.mercatus.org) is a research center at George Mason University that advances knowledge about how markets solve problems and help us lead happier, healthier, and richer lives. For more than 40 years, Mercatus has supported leading talent and scholarship in the mainline economics tradition, applying rigorous research to real-world concerns. Through our continuing efforts to bridge the gap between theory and practice, we strive to realize a world where markets operate at their full potential to increase abundance, civility, and well-being.

# The Virginia Zoning Atlas

Visit the full screen version by clicking [here](https://housingforwardva.shinyapps.io/va_zoning_atlas/).

```{=html}

<iframe id="vza" src="https://housingforwardva.shinyapps.io/va_zoning_atlas/" style="border: none; width: 700px; height: 550px" frameborder="0"></iframe>

```

