## Hook 1

Have you ever wondered why...

- A gas station went up on that corner instead of a new park?
- The mall has so much parking around it?
- That new apartment building is so tall?

## Hook 2

...it’s ZONING!

- Zoning is a collection of local laws that tell property owners what they can and can’t do with their property
- Makes total sense that we want to collectively influence what gets built where, right?

## Problem

Unfortunately...

- The regulatory fabric that shapes our community isn’t producing the results we need
- Zoning codes (and the development process) are difficult for average people to wrap their head around
- Many communities still have zoning schemes rooted in early 20th century racist planning practices

## Goals

- Know where zoning came from
- Understand the nuts and bolts of zoning
- Be ready to dive into the VZA

## Origins

- "Usual" story (improve living conditions in cities)
- "Actual" story

[Hopkins v. City of Richmond](https://cite.case.law/va/117/692/)

## Virginia

```

1908: Richmond's first zoning ordinance (heights and arrangements)
1910: Upheld by Virginia Supreme Court (inspired 1916 NYC ordinance)
1911: Richmond's segregation zoning ordinance

```